In [1]:
import numpy as np
import pandas as pd
import datetime

In [33]:
def gamelag(gm):
    yr,wk=(gm[:4],gm[4:])
    if wk=='1':
        return str(int(yr)-1)+'17'
    else:
        return yr+str(int(wk)-1)

In [3]:
strts=pd.to_datetime(['2009-09-10','2010-09-09','2011-09-08','2012-09-05','2013-09-05','2014-09-04','2015-09-10','2016-09-08','2017-09-07','2018-09-06','2019-09-05','2020-09-05'], format='%Y-%m-%d')
yrs=[2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
bins=pd.IntervalIndex.from_tuples([(strts[i],strts[i+1]) for i in range(len(strts)-1)], closed='left')

main=pd.read_csv("nflscrapr/NFL Play by Play 2009-2018 (v5).csv")
main['game_date'] = pd.to_datetime(main['game_date'], format='%Y-%m-%d')
main['year']=pd.cut(main['game_date'],bins).map(dict(zip(bins,yrs))).astype(int)
main['ssn_start']=main['year'].map(dict(zip(yrs,strts[:-1])))
main['week']=((main['game_date']-main['ssn_start']).astype(str).str.split(" ", expand=True)[0].astype(int)//7)+1

/home/kark/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (42,166,167,168,169,174,175,178,179,182,183,188,189,190,191,194,195,203,204,205,218,219,220,231,232,233,238,240,241,249) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
main

,play_id,game_id,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,...,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv,year,ssn_start,week
0,46,2009091000,PIT,TEN,PIT,home,TEN,TEN,30.0,2009-09-10,...,0,NaN,NaN,0.0,0.0,0.0,0.0,2009,2009-09-10,1
1,68,2009091000,PIT,TEN,PIT,home,TEN,PIT,58.0,2009-09-10,...,0,NaN,NaN,0.0,0.0,0.0,0.0,2009,2009-09-10,1
2,92,2009091000,PIT,TEN,PIT,home,TEN,PIT,53.0,2009-09-10,...,0,NaN,NaN,0.0,0.0,0.0,0.0,2009,2009-09-10,1
3,113,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,...,0,NaN,NaN,0.0,0.0,0.0,0.0,2009,2009-09-10,1
4,139,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,...,0,NaN,NaN,0.0,0.0,0.0,0.0,2009,2009-09-10,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449366,4059,2018121700,CAR,NO,CAR,home,NO,CAR,66.0,2018-12-17,...,0,NaN,NaN,0.0,0.0,0.0,0.0,2018,2018-09-06,15
449367,4081,2018121700,CAR,NO,CAR,home,NO,CAR,66.0,2018-12-17,...,0,NaN,NaN,0.0,0.0,0.0,0.0,2018,2018-09-06,15
449368,4106,2018121700,CAR,NO,CAR,home,NO,CAR,61.0,2018-12-17,...,0,NaN,NaN,0.0,0.0,0.0,0.0,2018,2018-09-06,15
449369,4128,2018121700,CAR,NO,NO,away,CAR,CAR,39.0,2018-12-17,...,0,NaN,NaN,0.0,0.0,0.0,0.0,2018,2018-09-06,15
449370,4150,2018121700,CAR,NO,NaN,NaN,NaN,CAR,NaN,2018-12-17,...,0,NaN,NaN,NaN,NaN,NaN,NaN,2018,2018-09-06,15

In [56]:
for i in main.columns:
    print(i)

play_id
game_id
home_team
away_team
posteam
posteam_type
defteam
side_of_field
yardline_100
game_date
quarter_seconds_remaining
half_seconds_remaining
game_seconds_remaining
game_half
quarter_end
drive
sp
qtr
down
goal_to_go
time
yrdln
ydstogo
ydsnet
desc
play_type
yards_gained
shotgun
no_huddle
qb_dropback
qb_kneel
qb_spike
qb_scramble
pass_length
pass_location
air_yards
yards_after_catch
run_location
run_gap
field_goal_result
kick_distance
extra_point_result
two_point_conv_result
home_timeouts_remaining
away_timeouts_remaining
timeout
timeout_team
td_team
posteam_timeouts_remaining
defteam_timeouts_remaining
total_home_score
total_away_score
posteam_score
defteam_score
score_differential
posteam_score_post
defteam_score_post
score_differential_post
no_score_prob
opp_fg_prob
opp_safety_prob
opp_td_prob
fg_prob
safety_prob
td_prob
extra_point_prob
two_point_conversion_prob
ep
epa
total_home_epa
total_away_epa
total_home_rush_epa
total_away_rush_epa
total_home_pass_epa
total_away_pass_epa
air_epa
yac_epa
comp_air_epa
comp_yac_epa
total_home_comp_air_epa
total_away_comp_air_epa
total_home_comp_yac_epa
total_away_comp_yac_epa
total_home_raw_air_epa
total_away_raw_air_epa
total_home_raw_yac_epa
total_away_raw_yac_epa
wp
def_wp
home_wp
away_wp
wpa
home_wp_post
away_wp_post
total_home_rush_wpa
total_away_rush_wpa
total_home_pass_wpa
total_away_pass_wpa
air_wpa
yac_wpa
comp_air_wpa
comp_yac_wpa
total_home_comp_air_wpa
total_away_comp_air_wpa
total_home_comp_yac_wpa
total_away_comp_yac_wpa
total_home_raw_air_wpa
total_away_raw_air_wpa
total_home_raw_yac_wpa
total_away_raw_yac_wpa
punt_blocked
first_down_rush
first_down_pass
first_down_penalty
third_down_converted
third_down_failed
fourth_down_converted
fourth_down_failed
incomplete_pass
interception
punt_inside_twenty
punt_in_endzone
punt_out_of_bounds
punt_downed
punt_fair_catch
kickoff_inside_twenty
kickoff_in_endzone
kickoff_out_of_bounds
kickoff_downed
kickoff_fair_catch
fumble_forced
fumble_not_forced
fumble_out_of_bounds
solo_tackle
safety
penalty
tackled_for_loss
fumble_lost
own_kickoff_recovery
own_kickoff_recovery_td
qb_hit
rush_attempt
pass_attempt
sack
touchdown
pass_touchdown
rush_touchdown
return_touchdown
extra_point_attempt
two_point_attempt
field_goal_attempt
kickoff_attempt
punt_attempt
fumble
complete_pass
assist_tackle
lateral_reception
lateral_rush
lateral_return
lateral_recovery
passer_player_id
passer_player_name
receiver_player_id
receiver_player_name
rusher_player_id
rusher_player_name
lateral_receiver_player_id
lateral_receiver_player_name
lateral_rusher_player_id
lateral_rusher_player_name
lateral_sack_player_id
lateral_sack_player_name
interception_player_id
interception_player_name
lateral_interception_player_id
lateral_interception_player_name
punt_returner_player_id
punt_returner_player_name
lateral_punt_returner_player_id
lateral_punt_returner_player_name
kickoff_returner_player_name
kickoff_returner_player_id
lateral_kickoff_returner_player_id
lateral_kickoff_returner_player_name
punter_player_id
punter_player_name
kicker_player_name
kicker_player_id
own_kickoff_recovery_player_id
own_kickoff_recovery_player_name
blocked_player_id
blocked_player_name
tackle_for_loss_1_player_id
tackle_for_loss_1_player_name
tackle_for_loss_2_player_id
tackle_for_loss_2_player_name
qb_hit_1_player_id
qb_hit_1_player_name
qb_hit_2_player_id
qb_hit_2_player_name
forced_fumble_player_1_team
forced_fumble_player_1_player_id
forced_fumble_player_1_player_name
forced_fumble_player_2_team
forced_fumble_player_2_player_id
forced_fumble_player_2_player_name
solo_tackle_1_team
solo_tackle_2_team
solo_tackle_1_player_id
solo_tackle_2_player_id
solo_tackle_1_player_name
solo_tackle_2_player_name
assist_tackle_1_player_id
assist_tackle_1_player_name
assist_tackle_1_team
assist_tackle_2_player_id
assist_tackle_2_player_name
assist_tackle_2_team
assist_tackle_3_player_id
assist_tackle_3_player_name
assist_tackle_3_team
assist_tackle_4_player_id
assist_tackle_4_player_name
assist_tackle_4_team
pass_defense_1_player_id
pass_defense_1_player_name
pass_defense_2_player_id
pass_defense_2_player_name
fumbled_1_team
fumbled_1_player_id
fumbled_1_player_name
fumbled_2_player_id
fumbled_2_player_name
fumbled_2_team
fumble_recovery_1_team
fumble_recovery_1_yards
fumble_recovery_1_player_id
fumble_recovery_1_player_name
fumble_recovery_2_team
fumble_recovery_2_yards
fumble_recovery_2_player_id
fumble_recovery_2_player_name
return_team
return_yards
penalty_team
penalty_player_id
penalty_player_name
penalty_yards
replay_or_challenge
replay_or_challenge_result
penalty_type
defensive_two_point_attempt
defensive_two_point_conv
defensive_extra_point_attempt
defensive_extra_point_conv
year
ssn_start
week

In [6]:
incols=['rusher_player_id','rusher_player_name','week','year','yards_gained','rush_attempt','rush_touchdown']
rush=main[(main['rush_attempt']==1)][incols]

In [40]:
smcols=['yards_gained','rush_attempt','rush_touchdown']
his=30
samp=rush[['rusher_player_id','rusher_player_name','week','year']+smcols].groupby(['rusher_player_id','rusher_player_name','week','year']).sum().reset_index()
samp['Game0']=samp['year'].astype(str)+samp['week'].astype(str)
rnm={}
for i in range(1,his+1):
    samp=samp.drop_duplicates()
    print(i)
    print(len(samp))
    lagl=[]
    for col in smcols:
        lagl.append(col+str(i))
        rnm[col]=col+str(i)
    rnm['Game0']='Game'+str(i)
    tmp=samp.rename(columns=rnm)
    samp['Game'+str(i)]=samp['Game'+str(i-1)].apply(gamelag)
    samp=samp.merge(tmp[['Game'+str(i),'rusher_player_id']+lagl], how='left', on=['Game'+str(i),'rusher_player_id'])

1
20196
2
20196
3
20196
4
20196
5
20196
6
20196
7
20196
8
20196
9
20196
10
20197
11
20198
12
20199
13
20200
14
20200
15
20200
16
20200
17
20201
18
20202
19
20203
20
20204
21
20205
22
20206
23
20207
24
20207
25
20208
26
20209
27
20209
28
20209
29
20209
30
20210

In [41]:
samp

,rusher_player_id,rusher_player_name,week,year,yards_gained,rush_attempt,rush_touchdown,Game0,Game1,yards_gained1,...,rush_attempt28,rush_touchdown28,Game29,yards_gained29,rush_attempt29,rush_touchdown29,Game30,yards_gained30,rush_attempt30,rush_touchdown30
0,00-0000865,C.Batch,2,2010,0.0,1.0,0.0,20102,20101,NaN,...,NaN,NaN,20087,NaN,NaN,NaN,20086,NaN,NaN,NaN
1,00-0000865,C.Batch,3,2010,26.0,5.0,0.0,20103,20102,0.0,...,NaN,NaN,20088,NaN,NaN,NaN,20087,NaN,NaN,NaN
2,00-0000865,C.Batch,4,2010,4.0,1.0,0.0,20104,20103,26.0,...,NaN,NaN,20089,NaN,NaN,NaN,20088,NaN,NaN,NaN
3,00-0000865,C.Batch,13,2011,-2.0,3.0,0.0,201113,201112,NaN,...,1.0,0.0,20101,NaN,NaN,NaN,200917,NaN,NaN,NaN
4,00-0001231,J.Bidwell,1,2010,0.0,1.0,0.0,20101,200917,NaN,...,NaN,NaN,20086,NaN,NaN,NaN,20085,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20213,00-0034869,S.Darnold,6,2018,8.0,6.0,0.0,20186,20185,5.0,...,NaN,NaN,201611,NaN,NaN,NaN,201610,NaN,NaN,NaN
20214,00-0034869,S.Darnold,7,2018,18.0,6.0,1.0,20187,20186,8.0,...,NaN,NaN,201612,NaN,NaN,NaN,201611,NaN,NaN,NaN
20215,00-0034869,S.Darnold,8,2018,22.0,5.0,0.0,20188,20187,18.0,...,NaN,NaN,201613,NaN,NaN,NaN,201612,NaN,NaN,NaN
20216,00-0034869,S.Darnold,14,2018,10.0,4.0,0.0,201814,201813,NaN,...,NaN,NaN,20172,NaN,NaN,NaN,20171,NaN,NaN,NaN
20217,00-0034869,S.Darnold,15,2018,35.0,6.0,0.0,201815,201814,10.0,...,NaN,NaN,20173,NaN,NaN,NaN,20172,NaN,NaN,NaN

In [23]:
samp[(samp['rusher_player_id']=='00-0025394') & (samp['year']==2012)]

,rusher_player_id,rusher_player_name,week,year,yards_gained,rush_attempt,rush_touchdown,Game0,Game1,yards_gained1,...,rush_attempt21,rush_touchdown21,Game22,yards_gained22,rush_attempt22,rush_touchdown22,Game23,yards_gained23,rush_attempt23,rush_touchdown23
4768,00-0025394,A.Peterson,1,2012,84.0,17.0,2.0,20121,201117,NaN,...,14.0,0.0,201013,107.0,16.0,3.0,201012,36.0,6.0,1.0
4778,00-0025394,A.Peterson,2,2012,60.0,16.0,0.0,20122,20121,84.0,...,NaN,NaN,201014,26.0,14.0,0.0,201013,107.0,16.0,3.0
4787,00-0025394,A.Peterson,3,2012,86.0,25.0,0.0,20123,20122,60.0,...,22.0,1.0,201015,NaN,NaN,NaN,201014,26.0,14.0,0.0
4794,00-0025394,A.Peterson,4,2012,102.0,21.0,0.0,20124,20123,86.0,...,14.0,0.0,201016,118.0,22.0,1.0,201015,NaN,NaN,NaN
4801,00-0025394,A.Peterson,5,2012,88.0,17.0,0.0,20125,20124,102.0,...,16.0,0.0,201017,31.0,14.0,0.0,201016,118.0,22.0,1.0
4806,00-0025394,A.Peterson,6,2012,79.0,17.0,0.0,20126,20125,88.0,...,25.0,2.0,20111,98.0,16.0,0.0,201017,31.0,14.0,0.0
4814,00-0025394,A.Peterson,7,2012,153.0,23.0,1.0,20127,20126,79.0,...,17.0,1.0,20112,120.0,25.0,2.0,20111,98.0,16.0,0.0
4822,00-0025394,A.Peterson,8,2012,123.0,15.0,1.0,20128,20127,153.0,...,23.0,0.0,20113,78.0,17.0,1.0,20112,120.0,25.0,2.0
4827,00-0025394,A.Peterson,9,2012,182.0,17.0,2.0,20129,20128,123.0,...,29.0,3.0,20114,80.0,23.0,0.0,20113,78.0,17.0,1.0
4835,00-0025394,A.Peterson,10,2012,173.0,28.0,1.0,201210,20129,182.0,...,12.0,1.0,20115,122.0,29.0,3.0,20114,80.0,23.0,0.0
4849,00-0025394,A.Peterson,12,2012,108.0,18.0,0.0,201212,201211,NaN,...,21.0,1.0,20117,175.0,24.0,1.0,20116,39.0,12.0,1.0
4856,00-0025394,A.Peterson,13,2012,210.0,21.0,1.0,201213,201212,108.0,...,NaN,NaN,20118,86.0,21.0,1.0,20117,175.0,24.0,1.0
4862,00-0025394,A.Peterson,14,2012,154.0,31.0,2.0,201214,201213,210.0,...,14.0,1.0,20119,NaN,NaN,NaN,20118,86.0,21.0,1.0
4868,00-0025394,A.Peterson,15,2012,212.0,24.0,1.0,201215,201214,154.0,...,6.0,1.0,201110,51.0,14.0,1.0,20119,NaN,NaN,NaN
4875,00-0025394,A.Peterson,16,2012,86.0,25.0,0.0,201216,201215,212.0,...,NaN,NaN,201111,26.0,6.0,1.0,201110,51.0,14.0,1.0
4880,00-0025394,A.Peterson,17,2012,199.0,34.0,1.0,201217,201216,86.0,...,NaN,NaN,201112,NaN,NaN,NaN,201111,26.0,6.0,1.0

In [25]:
samp.distinct

AttributeError: 'DataFrame' object has no attribute 'distinct'

In [67]:
samp.iloc[9001]

rusher_player_id      00-0027029
rusher_player_name       L.McCoy
week                           6
year                        2014
yards_gained                 149
rush_attempt                  22
rush_touchdown                 0
Game0                      20146
Game1                      20145
yards_gained1                 81
rush_attempt1                 24
rush_touchdown1                0
Game2                      20144
yards_gained2                 17
rush_attempt2                 10
rush_touchdown2                0
Game3                      20143
yards_gained3                 22
rush_attempt3                 20
rush_touchdown3                0
Game4                      20142
yards_gained4                 79
rush_attempt4                 20
rush_touchdown4                1
Game5                      20141
yards_gained5                 74
rush_attempt5                 21
rush_touchdown5                0
Name: 9001, dtype: object

In [117]:
samp[samp['Yards']>200]

           Last First  Week  SeasonYear  Yards  IsRush  IsTouchdown
123       AJAYI     J     6        2016    204      25            2
149       AJAYI     J    16        2016    206      32            1
738        BELL     L     6        2017    203      32            1
756        BELL     L    11        2014    204      33            1
765        BELL     L    14        2016    236      38            3
2392    CROWELL     I     5        2018    216      14            1
3540  FOURNETTE     L     4        2019    207      22            0
4220     GURLEY     T     6        2018    208      28            2
4440      HENRY     D    14        2018    238      17            4
5452    JOHNSON     K     4        2019    225      26            1
6512     MARTIN     D    11        2015    235      27            0
8017   PETERSON     A    10        2015    203      26            1
8319      RAWLS     T    11        2015    209      30            1

In [169]:
main['DefenseTeam'].value_counts()

NYG    8286
CLE    8233
MIA    8174
KC     8157
CIN    8154
SF     8135
JAX    8101
ARI    8094
PHI    8091
TB     8073
TEN    8072
OAK    8057
DEN    8035
NYJ    8030
LA     8015
GB     7965
ATL    7948
HOU    7886
BUF    7864
CHI    7848
WAS    7847
IND    7842
MIN    7829
SEA    7816
BAL    7799
NO     7795
DET    7783
CAR    7765
NE     7739
DAL    7726
PIT    7709
SD     4251
LAC    3479
Name: DefenseTeam, dtype: int64